apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq-chart.fullname" . }}
  labels:
{{ include "rabbitmq-chart.labels" . | indent 4 }}
spec:
  loadBalancerIP: {{ .Values.service.publicip }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port1 }}
      targetPort: {{ .Values.service.port1 }}
      protocol: TCP
      name: port-1
    - port: {{ .Values.service.port2 }}
      targetPort: {{ .Values.service.port2 }}
      protocol: TCP
      name: port-2
  selector:
    app.kubernetes.io/name: {{ include "rabbitmq-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
