apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: certificate
  namespace: cert-manager
spec:
  secretName: certificate
  dnsNames:
  - [NGINX_INGRESS_DNS].[CLUSTER_LOCATION].cloudapp.azure.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - [NGINX_INGRESS_DNS].[CLUSTER_LOCATION].cloudapp.azure.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer